use crate::armor::Armor;
use crate::skill::SkillId;

pub const ARMS_ARMORS: [Armor; 6] = [
    Armor {
        name: "Gore Vambraces α",
        set: "Gore α",
        defense: 60,
        slots: &[2, 1],
        fire_res: -2,
        water_res: 3,
        thunder_res: -1,
        ice_res: 2,
        dragon_res: -1,
        skills: &[
            (SkillId::Constitution, 2),
            (SkillId::EvadeWindow, 1),
            (SkillId::GoreMagalasTyranny, 1),
            (SkillId::ScalingProwess, 1),
        ],
    },
    Armor {
        name: "Gore Vambraces β",
        set: "Gore β",
        defense: 60,
        slots: &[2, 2],
        fire_res: -2,
        water_res: 3,
        thunder_res: -1,
        ice_res: 2,
        dragon_res: -1,
        skills: &[
            (SkillId::Constitution, 1),
            (SkillId::EvadeWindow, 1),
            (SkillId::GoreMagalasTyranny, 1),
            (SkillId::ScaleLayering, 1),
        ],
    },
    Armor {
        name: "Arkvulcan Vambraces α",
        set: "Arkveld α",
        defense: 66,
        slots: &[2, 2],
        fire_res: 2,
        water_res: 0,
        thunder_res: -1,
        ice_res: 0,
        dragon_res: -3,
        skills: &[
            (SkillId::ConvertElement, 1),
            (SkillId::RecoverySpeed, 1),
            (SkillId::ArkveldsHunger, 1),
            (SkillId::FortifyingPelt, 1),
        ],
    },
    Armor {
        name: "Arkvulcan Vambraces β",
        set: "Arkveld β",
        defense: 66,
        slots: &[2, 2, 1],
        fire_res: 2,
        water_res: 0,
        thunder_res: -1,
        ice_res: 0,
        dragon_res: -3,
        skills: &[
            (SkillId::ConvertElement, 1),
            (SkillId::ArkveldsHunger, 1),
            (SkillId::AlluringPelt, 1),
        ],
    },
    Armor {
        name: "G. Arkveld Vambraces α",
        set: "Guardian Arkveld α",
        defense: 66,
        slots: &[1],
        fire_res: 2,
        water_res: 0,
        thunder_res: -1,
        ice_res: 0,
        dragon_res: -4,
        skills: &[
            (SkillId::WeaknessExploit, 2),
            (SkillId::BlightResistance, 1),
            (SkillId::GuardianArkveldsVitality, 1),
            (SkillId::GuardiansPulse, 1),
        ],
    },
    Armor {
        name: "G. Arkveld Vambraces β",
        set: "Guardian Arkveld β",
        defense: 66,
        slots: &[1, 1, 1],
        fire_res: 2,
        water_res: 0,
        thunder_res: -1,
        ice_res: 0,
        dragon_res: -4,
        skills: &[
            (SkillId::WeaknessExploit, 2),
            (SkillId::GuardianArkveldsVitality, 1),
            (SkillId::GuardiansProtection, 1),
        ],
    },
];
