use crate::armor::Armor;
use crate::skill::SkillId;

pub const LEGS_ARMORS: [Armor; 6] = [
    Armor {
        name: "Gore Greaves α",
        set: "Gore α",
        defense: 60,
        slots: &[3, 1],
        fire_res: -2,
        water_res: 3,
        thunder_res: -1,
        ice_res: 2,
        dragon_res: -1,
        skills: &[
            (SkillId::FlinchFree, 2),
            (SkillId::Antivirus, 1),
            (SkillId::GoreMagalasTyranny, 1),
            (SkillId::ScalingProwess, 1),
        ],
    },
    Armor {
        name: "Gore Greaves β",
        set: "Gore β",
        defense: 60,
        slots: &[3, 1, 1],
        fire_res: -2,
        water_res: 3,
        thunder_res: -1,
        ice_res: 2,
        dragon_res: -1,
        skills: &[
            (SkillId::Antivirus, 1),
            (SkillId::FlinchFree, 1),
            (SkillId::GoreMagalasTyranny, 1),
            (SkillId::ScaleLayering, 1),
        ],
    },
    Armor {
        name: "Arkvulcan Greaves α",
        set: "Arkveld α",
        defense: 66,
        slots: &[2, 1],
        fire_res: 2,
        water_res: 0,
        thunder_res: -1,
        ice_res: 0,
        dragon_res: -3,
        skills: &[
            (SkillId::QuickSheathe, 2),
            (SkillId::ConvertElement, 1),
            (SkillId::ArkveldsHunger, 1),
            (SkillId::FortifyingPelt, 1),
        ],
    },
    Armor {
        name: "Arkvulcan Greaves β",
        set: "Arkveld β",
        defense: 66,
        slots: &[3, 1],
        fire_res: 2,
        water_res: 0,
        thunder_res: -1,
        ice_res: 0,
        dragon_res: -3,
        skills: &[
            (SkillId::ConvertElement, 1),
            (SkillId::QuickSheathe, 1),
            (SkillId::ArkveldsHunger, 1),
            (SkillId::AlluringPelt, 1),
        ],
    },
    Armor {
        name: "G. Arkveld Greaves α",
        set: "Guardian Arkveld α",
        defense: 66,
        slots: &[],
        fire_res: 2,
        water_res: 0,
        thunder_res: -1,
        ice_res: 0,
        dragon_res: -4,
        skills: &[
            (SkillId::ElementalAbsorption, 2),
            (SkillId::WeaknessExploit, 1),
            (SkillId::GuardianArkveldsVitality, 1),
            (SkillId::GuardiansPulse, 1),
        ],
    },
    Armor {
        name: "G. Arkveld Greaves β",
        set: "Guardian Arkveld β",
        defense: 66,
        slots: &[2, 1],
        fire_res: 2,
        water_res: 0,
        thunder_res: -1,
        ice_res: 0,
        dragon_res: -4,
        skills: &[
            (SkillId::WeaknessExploit, 1),
            (SkillId::ElementalAbsorption, 1),
            (SkillId::GuardianArkveldsVitality, 1),
            (SkillId::GuardiansProtection, 1),
        ],
    },
];
