use crate::skill::SkillId;
use crate::weapon::{Element, Sharpness, Weapon, WeaponType};

pub const LANCES: [Weapon; 20] = [
    Weapon {
        name: "Esperanza Lance",
        tree: "Expedition",
        attack: 210,
        affinity: 0,
        element: Element::None,
        sharpness: Sharpness {
            red: 50,
            orange: 60,
            yellow: 60,
            green: 60,
            blue: 40,
            white: 130,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalEye, 2), (SkillId::SpeedSharpening, 2)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Shining Pillar",
        tree: "G. Rathalos",
        attack: 220,
        affinity: 15,
        element: Element::Fire(25),
        sharpness: Sharpness {
            red: 50,
            orange: 150,
            yellow: 50,
            green: 40,
            blue: 40,
            white: 70,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalElement, 1), (SkillId::MastersTouch, 1)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Sandsea Prallaya",
        tree: "Balahara",
        attack: 210,
        affinity: 10,
        element: Element::Water(25),
        sharpness: Sharpness {
            red: 40,
            orange: 30,
            yellow: 100,
            green: 80,
            blue: 70,
            white: 80,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::OffensiveGuard, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Indra Clairlance",
        tree: "Rey Dau",
        attack: 220,
        affinity: 0,
        element: Element::Thunder(25),
        // For the Indra Clairlance in particular, I have gone into the training area and hit the
        // dummy 350 times (without Handicraft or any other sharpness skills) to ensure sharpness
        // drops after the correct number of hits, which it did. Thus these sharpness numbers are
        // the only ones I've explicitly confirmed myself. Sharpness numbers for all other Lances
        // come from counting the pixels on sharpness bars.
        sharpness: Sharpness {
            red: 10,
            orange: 10,
            yellow: 110,
            green: 70,
            blue: 70,
            white: 130,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::Guard, 2), (SkillId::OffensiveGuard, 1)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Chrome Lance",
        tree: "Ore",
        attack: 220,
        affinity: 0,
        element: Element::None,
        sharpness: Sharpness {
            red: 30,
            orange: 60,
            yellow: 90,
            green: 70,
            blue: 50,
            white: 100,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::GuardUp, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Rompo Tetrotox",
        tree: "Rompopolo",
        attack: 220,
        affinity: 0,
        element: Element::Poison(25),
        sharpness: Sharpness {
            red: 40,
            orange: 50,
            yellow: 100,
            green: 30,
            blue: 100,
            white: 80,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::GuardUp, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Abaddonian Osminog",
        tree: "Nu Udra",
        attack: 230,
        affinity: -15,
        element: Element::Fire(25),
        sharpness: Sharpness {
            red: 100,
            orange: 20,
            yellow: 100,
            green: 50,
            blue: 50,
            white: 80,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::OffensiveGuard, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Hard Bone Lance",
        tree: "Bone",
        attack: 230,
        affinity: 0,
        element: Element::None,
        sharpness: Sharpness {
            red: 50,
            orange: 60,
            yellow: 70,
            green: 70,
            blue: 150,
            white: 0,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::GuardUp, 3), (SkillId::AttackBoost, 1)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Windpierce Tsukibami",
        tree: "Hirabami",
        attack: 220,
        affinity: 0,
        element: Element::Ice(25),
        sharpness: Sharpness {
            red: 50,
            orange: 50,
            yellow: 50,
            green: 30,
            blue: 120,
            white: 100,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::Guard, 3), (SkillId::Airborne, 1)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Bequeathed Regret",
        tree: "G. Ebony",
        attack: 210,
        affinity: 10,
        element: Element::Dragon(35),
        sharpness: Sharpness {
            red: 50,
            orange: 50,
            yellow: 80,
            green: 80,
            blue: 100,
            white: 40,
            handicraft_locked: 0,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::OffensiveGuard, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Firetrail Kaminet",
        tree: "Quematrice",
        attack: 240,
        affinity: 5,
        element: Element::Fire(20),
        sharpness: Sharpness {
            red: 60,
            orange: 70,
            yellow: 80,
            green: 80,
            blue: 110,
            white: 0,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::Guard, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Fierceborer Dubhanith",
        tree: "Doshaguma",
        attack: 240,
        affinity: -5,
        element: Element::None,
        sharpness: Sharpness {
            red: 50,
            orange: 100,
            yellow: 110,
            green: 50,
            blue: 40,
            white: 50,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 20,
        skills: &[(SkillId::PunishingDraw, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "G. Purifying Beaumains",
        tree: "G. Arkveld",
        attack: 240,
        affinity: -10,
        element: Element::Dragon(20),
        sharpness: Sharpness {
            red: 100,
            orange: 70,
            yellow: 50,
            green: 80,
            blue: 60,
            white: 40,
            handicraft_locked: 50,
        },
        slots: &[3, 3, 1],
        defense: 0,
        skills: &[(SkillId::Guard, 2)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Purifying Beaumains",
        tree: "Arkveld",
        attack: 220,
        affinity: 0,
        element: Element::Dragon(35),
        sharpness: Sharpness {
            red: 50,
            orange: 50,
            yellow: 50,
            green: 70,
            blue: 80,
            white: 100,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::Guard, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Gloomborer Urshanith",
        tree: "G. Doshaguma",
        attack: 250,
        affinity: -15,
        element: Element::None,
        sharpness: Sharpness {
            red: 50,
            orange: 70,
            yellow: 90,
            green: 90,
            blue: 70,
            white: 30,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::OffensiveGuard, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Lala Aviculari",
        tree: "Lala Barina",
        attack: 200,
        affinity: 15,
        element: Element::Paralysis(25),
        sharpness: Sharpness {
            red: 70,
            orange: 50,
            yellow: 30,
            green: 60,
            blue: 40,
            white: 150,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalDraw, 2), (SkillId::CriticalStatus, 1)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Spear of Prominence",
        tree: "Rathalos",
        attack: 210,
        affinity: 10,
        element: Element::Fire(35),
        sharpness: Sharpness {
            red: 100,
            orange: 70,
            yellow: 50,
            green: 40,
            blue: 50,
            white: 90,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalBoost, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Fieberschild",
        tree: "Gore Magala",
        attack: 210,
        affinity: 20,
        element: Element::Dragon(25),
        sharpness: Sharpness {
            red: 50,
            orange: 50,
            yellow: 80,
            green: 60,
            blue: 40,
            white: 120,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalElement, 2)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Gravios Lance",
        tree: "Gravios",
        attack: 250,
        affinity: -15,
        element: Element::Blast(35),
        sharpness: Sharpness {
            red: 90,
            orange: 70,
            yellow: 70,
            green: 70,
            blue: 100,
            white: 0,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 30,
        skills: &[(SkillId::GuardUp, 3)],
        weapon_type: WeaponType::Lance,
    },
    Weapon {
        name: "Babel Spear",
        tree: "Workshop",
        attack: 220,
        affinity: 0,
        element: Element::None,
        sharpness: Sharpness {
            red: 20,
            orange: 60,
            yellow: 60,
            green: 50,
            blue: 130,
            white: 80,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalDraw, 3), (SkillId::Guard, 1)],
        weapon_type: WeaponType::Lance,
    },
];
