use crate::skill::SkillId;
use crate::weapon::{Element, Sharpness, Weapon};

pub const LANCES: [Weapon; 21] = [
    Weapon {
        name: "Esperanza Lance",
        tree: "Expedition",
        attack: 210,
        affinity: 0,
        element: Element::None,
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalEye, 2), (SkillId::SpeedSharpening, 2)],
    },
    Weapon {
        name: "Shining Pillar",
        tree: "G. Rathalos",
        attack: 220,
        affinity: 15,
        element: Element::Fire(25),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalElement, 1), (SkillId::MastersTouch, 1)],
    },
    Weapon {
        name: "Sandsea Prallaya",
        tree: "Balahara",
        attack: 210,
        affinity: 10,
        element: Element::Water(25),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::OffensiveGuard, 3)],
    },
    Weapon {
        name: "Indra Clairlance",
        tree: "Rey Dau",
        attack: 220,
        affinity: 0,
        element: Element::Thunder(25),
        // For the Indra Clairlance in particular, I have gone into the training area and hit the
        // dummy 350 times (without Handicraft or any other sharpness skills) to ensure sharpness
        // drops after the correct number of hits, which it did. Thus these sharpness numbers are
        // the only ones I've explicitly confirmed myself. Sharpness numbers for all other Lances
        // come from counting the pixels on sharpness bars.
        sharpness: Sharpness {
            red: 10,
            orange: 10,
            yellow: 110,
            green: 70,
            blue: 70,
            white: 130,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::Guard, 2), (SkillId::OffensiveGuard, 1)],
    },
    Weapon {
        name: "Chrome Lance",
        tree: "Ore",
        attack: 220,
        affinity: 0,
        element: Element::None,
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::GuardUp, 3)],
    },
    Weapon {
        name: "Rompo Tetrotox",
        tree: "Rompopolo",
        attack: 220,
        affinity: 0,
        element: Element::Poison(25),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::GuardUp, 3)],
    },
    Weapon {
        name: "Abaddonian Osminog",
        tree: "Nu Udra",
        attack: 230,
        affinity: -15,
        element: Element::Fire(25),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::OffensiveGuard, 3)],
    },
    Weapon {
        name: "Hard Bone Lance",
        tree: "Bone",
        attack: 230,
        affinity: 0,
        element: Element::None,
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::GuardUp, 3), (SkillId::AttackBoost, 1)],
    },
    Weapon {
        name: "Windpierce Tsukibami",
        tree: "Hirabami",
        attack: 220,
        affinity: 0,
        element: Element::Ice(25),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::Guard, 3), (SkillId::Airborne, 1)],
    },
    Weapon {
        name: "Bequeathed Regret",
        tree: "G. Ebony",
        attack: 210,
        affinity: 10,
        element: Element::Dragon(35),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::OffensiveGuard, 3)],
    },
    Weapon {
        name: "Firetrail Kaminet",
        tree: "Quematrice",
        attack: 240,
        affinity: 5,
        element: Element::Fire(20),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::Guard, 3)],
    },
    Weapon {
        name: "Fierceborer Dubhanith",
        tree: "Doshaguma",
        attack: 240,
        affinity: -5,
        element: Element::None,
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 20,
        skills: &[(SkillId::PunishingDraw, 3)],
    },
    Weapon {
        name: "G. Purifying Beaumains",
        tree: "G. Arkveld",
        attack: 240,
        affinity: -10,
        element: Element::Dragon(20),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 3, 1],
        defense: 0,
        skills: &[(SkillId::Guard, 2)],
    },
    Weapon {
        name: "Purifying Beaumains",
        tree: "Arkveld",
        attack: 220,
        affinity: 0,
        element: Element::Dragon(35),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::Guard, 3)],
    },
    Weapon {
        name: "Hard Bone Lance",
        tree: "Bone",
        attack: 230,
        affinity: 0,
        element: Element::None,
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::GuardUp, 3), (SkillId::AttackBoost, 1)],
    },
    Weapon {
        name: "Gloomborer Urshanith",
        tree: "G. Doshaguma",
        attack: 250,
        affinity: -15,
        element: Element::None,
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::OffensiveGuard, 3)],
    },
    Weapon {
        name: "Lala Aviculari",
        tree: "Lala Barina",
        attack: 200,
        affinity: 15,
        element: Element::Paralysis(25),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalDraw, 2), (SkillId::CriticalStatus, 1)],
    },
    Weapon {
        name: "Spear of Prominence",
        tree: "Rathalos",
        attack: 210,
        affinity: 10,
        element: Element::Fire(35),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalBoost, 3)],
    },
    Weapon {
        name: "Fieberschild",
        tree: "Gore Magala",
        attack: 210,
        affinity: 20,
        element: Element::Dragon(25),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalElement, 2)],
    },
    Weapon {
        name: "Gravios Lance",
        tree: "Gravios",
        attack: 250,
        affinity: -15,
        element: Element::Blast(35),
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 30,
        skills: &[(SkillId::GuardUp, 3)],
    },
    Weapon {
        name: "Babel Spear",
        tree: "Workshop",
        attack: 220,
        affinity: 0,
        element: Element::None,
        // TODO: Determine correct sharpness values.
        sharpness: Sharpness {
            red: 1,
            orange: 1,
            yellow: 1,
            green: 1,
            blue: 1,
            white: 1,
            handicraft_locked: 50,
        },
        slots: &[3, 2, 1],
        defense: 0,
        skills: &[(SkillId::CriticalDraw, 3), (SkillId::Guard, 1)],
    },
];
